export const municipalCorporations = [
  { id: 'BMC', name: 'Brihanmumbai Municipal Corporation (BMC) - Mumbai' },
  { id: 'MCD', name: 'Municipal Corporation of Delhi (MCD) - Delhi' },
  { id: 'GCC', name: 'Greater Chennai Corporation (GCC) - Chennai' },
  { id: 'GHMC', name: 'Greater Hyderabad Municipal Corporation (GHMC) - Hyderabad' },
  { id: 'KMC', name: 'Kolkata Municipal Corporation (KMC) - Kolkata' },
  { id: 'BCCMC', name: 'Bengaluru Central City Municipal Corporation (BCCMC) - Bengaluru' },
  { id: 'AMC', name: 'Ahmedabad Municipal Corporation (AMC) - Ahmedabad' },
  { id: 'PMC_PUNE', name: 'Pune Municipal Corporation (PMC) - Pune' },
  { id: 'SMC', name: 'Surat Municipal Corporation (SMC) - Surat' },
  { id: 'JMC', name: 'Jaipur Municipal Corporation (JMC) - Jaipur' },
  { id: 'LMC', name: 'Lucknow Municipal Corporation (LMC) - Lucknow' },
  { id: 'PMC_PATNA', name: 'Patna Municipal Corporation (PMC) - Patna' }
];

export const getCorporationName = (id) => {
  const corp = municipalCorporations.find(c => c.id === id);
  return corp ? corp.name : 'Central City Dispatch (Unassigned)';
};

export const translationDictionary = {
  en: {
    topBarTitle: "CivicShield Municipal Portal",
    offlineSim: "Offline Mode Simulation",
    subHeader: "AI-Powered Civic Grievance Triage Desk",
    routingPlatform: "Automated Incident Routing Platform",
    mainHeadline: "Welcome to CivicShield",
    subHeadline: "Empowering Citizen-Driven Municipal Care. A public-trust interface designed to eradicate community safety hazards through secure, targeted reporting.",
    selectCorpCTA: "Select Your Municipal Corporation to Begin",
    accessPortalCTA: "Access Portal",
    heroBadgeText: "National Unified Portal for Municipal Grievance Redressal and Incident Routing.",
    faqQ1: "Autonomous Core Anti-Spam Gate",
    faqA1: "The integrated neural network parses infrastructure parameters instantly, denying invalid media submissions.",
    faqQ2: "Auto-Clustering Registry Systems",
    faqA2: "Identical coordinates match open files dynamically, updating your profile without double entries.",
    loginTitle: "Citizen & Staff Portal",
    loginDesc: "Establish a secure session to interact with CivicShield.",
    formName: "Full Name",
    formRole: "Portal Role",
    authSubmit: "Establish Secured Session",
    aiDeskTitle: "CIVIC-AI ASSISTANT",
    aiStatus: "Online • Secure Encryption",
    nodeTypeAnon: "Anonymous Node",
    nodeTypeActive: "Authenticated Node",
    uploadHeadline: "Upload Civic Issue Photo",
    uploadDesc: "Select an image from the simulated gallery below to generate a verified, geo-tagged civic work order.",
    unlockWorkspace: "Unlock Simulator Dashboard Workspace",
    aiProcessing: "Neural Net Evaluation Active: Validating Incident & Extracting Telemetry...",
    receiptHeader: "✅ Verified Municipal Work Order",
    recId: "Tracking Ref",
    recLoc: "Location",
    recDesc: "Classification",
    recSla: "Resolution SLA",
    recVotes: "Priority Votes",
    btnUpvote: "👍 Me Too / Affects My Neighborhood",
    voiceTrigger: "Read Aloud",
    shelfTitle: "Select Incident Visual From Gallery",
    m1: "Resolution Cycle Time",
    m2: "Active Field Deployments",
    m3: "Registry Deduplication Rate",
    heatmapTitle: "City-wide Escalation Overlay",
    spatialActive: "Interactive Spatial Overlay Active",
    adminTitle: "Municipal Dispatch Command",
    adminDesc: "Manage incoming citizen reports, assign workers, and track SLAs.",
    btnFf: "⏩ Fast-Forward Time (Breach SLA)",
    thId: "ID", thHazard: "Hazard Detail", thUrgency: "Status", thSla: "SLA Tracker", thAction: "Actions",
    navHome: "Home", navReport: "Report", navGrid: "Grid", navAdmin: "Worker Panel",
    voicePrompt: "Welcome to CivicShield. To report a hazard, log in and select a photo from your gallery.",
    alertFake: "❌ Invalid Image Detected: The uploaded image does not contain a recognizable public infrastructure hazard. Please upload a valid issue photo.",
    alertDup: "📢 Already Reported! This issue has been identified at this exact location. Your account has been linked.",
    alertOffline: "⚠️ Network connection lost. Your report has been securely cached locally and will auto-sync the moment a stable connection is re-established.",
    alertBreach: "⚠️ Escalated Alert: Reported issue breached SLA. Directly page City Worker Management.",
    unassignedSla: "Awaiting Assignment",
    title: "Citizen & Staff Portal",
    subtitle: "Establish Secured Session",
    labelName: "Full Name",
    placeholderName: "Enter your full name",
    labelRole: "Role",
    roleCitizen: "Citizen",
    roleAdmin: "City Admin/Worker",
    labelBranch: "Municipal Corporation",
    btnSubmit: "Establish Secured Session",
    btnCancel: "Cancel and Return to Home Page"
  },
  hi: {
    topBarTitle: "नागरिक शील्ड म्युनिसिपल पोर्टल",
    offlineSim: "ऑफ़लाइन मोड सिमुलेशन",
    subHeader: "एआई-संचालित नागरिक शिकायत ट्राइएज डेस्क",
    routingPlatform: "स्वचालित घटना रूटिंग प्लेटफ़ॉर्म",
    mainHeadline: "CivicShield में आपका स्वागत है",
    subHeadline: "नागरिक-प्रेरित नगरपालिका देखभाल को सशक्त बनाना। सुरक्षित, लक्षित रिपोर्टिंग के माध्यम से सामुदायिक सुरक्षा खतरों को खत्म करने के लिए डिज़ाइन किया गया एक सार्वजनिक-भरोसे का इंटरफ़ेस।",
    selectCorpCTA: "शुरू करने के लिए अपने नगर निगम का चयन करें",
    accessPortalCTA: "पोर्टल पर जाएं",
    heroBadgeText: "नगरपालिका शिकायत निवारण और घटना रूटिंग के लिए राष्ट्रीय एकीकृत पोर्टल।",
    faqQ1: "स्वायत्त कोर एंटी-स्पैम गेट",
    faqA1: "एकीकृत तंत्रिका नेटवर्क तुरंत बुनियादी ढांचे के मापदंडों को पार्स करता है, अमान्य मीडिया सबमिशन को रोकता है।",
    faqQ2: "ऑटो-क्लस्टरिंग रजिस्ट्री सिस्टम",
    faqA2: "समान निर्देशांक खुली फाइलों से गतिशील रूप से मेल खाते हैं, बिना दोहरी प्रविष्टि के आपकी प्रोफ़ाइल को अपडेट करते हैं।",
    loginTitle: "नागरिक और कर्मचारी पोर्टल",
    loginDesc: "सुरक्षित सत्र स्थापित करें",
    formName: "पूरा नाम",
    formRole: "पोर्टल भूमिका",
    authSubmit: "सुरक्षित सत्र स्थापित करें",
    aiDeskTitle: "नागरिक-एआई सहायक",
    aiStatus: "ऑनलाइन • सुरक्षित एन्क्रिप्शन",
    nodeTypeAnon: "अनाम नोड",
    nodeTypeActive: "प्रमाणित नोड",
    uploadHeadline: "नागरिक समस्या फोटो अपलोड करें",
    uploadDesc: "सत्यापित कार्य आदेश उत्पन्न करने के लिए नीचे दी गई गैलरी से एक छवि चुनें।",
    unlockWorkspace: "सिम्युलेटर डैशबोर्ड कार्यक्षेत्र को अनलॉक करें",
    aiProcessing: "न्यूरल नेट मूल्यांकन सक्रिय: घटना की सत्यता का सत्यापन...",
    receiptHeader: "✅ सत्यापित नगर पालिका कार्य आदेश",
    recId: "ट्रैकिंग संदर्भ",
    recLoc: "स्थान",
    recDesc: "वर्गीकरण",
    recSla: "समाधान SLA",
    recVotes: "प्राथमिकता वोट",
    btnUpvote: "👍 मैं भी / मेरे पड़ोस को प्रभावित करता है",
    voiceTrigger: "जोर से पढ़ें",
    shelfTitle: "गैलरी से घटना दृश्य का चयन करें",
    m1: "समाधान चक्र समय",
    m2: "सक्रिय क्षेत्र परिनियोजन",
    m3: "रजिस्ट्री डीडुप्लीकेशन दर",
    heatmapTitle: "शहर-व्यापी एस्केलेशन ओवरले",
    spatialActive: "इंटरएक्टिव स्थानिक ओवरले सक्रिय",
    adminTitle: "नगर प्रेषण कमान",
    adminDesc: "नागरिक रिपोर्ट प्रबंधित करें, श्रमिकों को सौंपें, और SLAs ट्रैक करें।",
    btnFf: "⏩ फास्ट-फॉरवर्ड समय (SLA का उल्लंघन)",
    thId: "आईडी", thHazard: "खतरा विवरण", thUrgency: "स्थिति", thSla: "SLA ट्रैकर", thAction: "कार्रवाई",
    navHome: "होम", navReport: "रिपोर्ट", navGrid: "ग्रिड", navAdmin: "कर्मचारी पैनल",
    voicePrompt: "नागरिक शील्ड में आपका स्वागत है। किसी खतरे की रिपोर्ट करने के लिए, लॉग इन करें और अपनी गैलरी से एक फोटो चुनें।",
    alertFake: "❌ अमान्य छवि का पता चला: अपलोड की गई छवि में सार्वजनिक बुनियादी ढांचे का कोई खतरा नहीं है।",
    alertDup: "📢 पहले ही रिपोर्ट किया जा चुका है! यह समस्या इसी स्थान पर पहचानी गई है। आपका खाता लिंक कर दिया गया है।",
    alertOffline: "⚠️ नेटवर्क कनेक्शन टूट गया। आपकी रिपोर्ट स्थानीय रूप से सहेजी गई है और कनेक्शन मिलते ही सिंक हो जाएगी।",
    alertBreach: "⚠️ एस्केलेटेड अलर्ट: रिपोर्ट की गई समस्या ने SLA का उल्लंघन किया।",
    unassignedSla: "कर्मचारी आवंटन की प्रतीक्षा है",
    title: "नागरिक और कर्मचारी पोर्टल",
    subtitle: "सुरक्षित सत्र स्थापित करें",
    labelName: "पूरा नाम",
    placeholderName: "अपना पूरा नाम दर्ज करें",
    labelRole: "भूमिका",
    roleCitizen: "नागरिक",
    roleAdmin: "नगर व्यवस्थापक/कर्मचारी",
    labelBranch: "नगर निगम",
    btnSubmit: "सुरक्षित सत्र स्थापित करें",
    btnCancel: "रद्द करें और मुख्य पृष्ठ पर लौटें"
  },
  kn: {
    topBarTitle: "ಸಿವಿಕ್ ಶೀಲ್ಡ್ ಮುನ್ಸಿಪಲ್ ಪೋರ್ಟಲ್",
    offlineSim: "ಆಫ್‌ಲೈನ್ ಮೋಡ್ ಸಿಮ್ಯುಲೇಶನ್",
    subHeader: "AI-ಚಾಲಿತ ನಾಗರಿಕ ಕುಂದುಕೊರತೆ ಡೆಸ್ಕ್",
    routingPlatform: "ಸ್ವಯಂಚಾಲಿತ ಘಟನೆ ರೂಟಿಂಗ್ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್",
    mainHeadline: "CivicShield ಗೆ ಸುಸ್ವಾಗತ",
    subHeadline: "ನಾಗರಿಕರಿಂದ ಚಾಲಿತ ಪುರಸಭೆಯ ಕಾಳಜಿಯನ್ನು ಸಬಲೀಕರಣಗೊಳಿಸುವುದು. ಸುರಕ್ಷಿತ, ಉದ್ದೇಶಿತ ವರದಿ ಮಾಡುವಿಕೆಯ ಮೂಲಕ ಸಮುದಾಯದ ಸುರಕ್ಷತೆಯ ಅಪಾಯಗಳನ್ನು ನಿರ್ಮೂಲನೆ ಮಾಡಲು ವಿನ್ಯಾಸಗೊಳಿಸಲಾದ ಸಾರ್ವಜನಿಕ-ವಿಶ್ವಾಸದ ಇಂಟರ್ಫೇಸ್.",
    selectCorpCTA: "ಪ್ರಾರಂಭಿಸಲು ನಿಮ್ಮ ಮುನ್ಸಿಪಲ್ ಕಾರ್ಪೊರೇಷನ್ ಆಯ್ಕೆಮಾಡಿ",
    accessPortalCTA: "ಪೋರ್ಟಲ್ ಪ್ರವೇಶಿಸಿ",
    heroBadgeText: "ನಾಗರಿಕ ಕುಂದುಕೊರತೆಗಳ ನಿವಾರಣೆ ಮತ್ತು ಘಟನೆ ರೂಟಿಂಗ್ಗಾಗಿ ರಾಷ್ಟ್ರೀಯ ಏಕೀಕೃತ ಪೋರ್ಟಲ್.",
    faqQ1: "ಸ್ವಾಯತ್ತ ಕೋರ್ ಆಂಟಿ-ಸ್ಪ್ಯಾಮ್ ಗೇಟ್",
    faqA1: "ಇಂಟಿಗ್ರೇಟೆಡ್ ನ್ಯೂರಲ್ ನೆಟ್‌ವರ್ಕ್ ಮೂಲಸೌಕರ್ಯ ನಿಯತಾಂಕಗಳನ್ನು ತಕ್ಷಣವೇ ಪಾರ್ಸ್ ಮಾಡುತ್ತದೆ, ಅಮಾನ್ಯ ಮಾಧ್ಯಮ ಸಲ್ಲಿಕೆಗಳನ್ನು ನಿರಾಕರಿಸುತ್ತದೆ.",
    faqQ2: "ಆಟೋ-ಕ್ಲಸ್ಟರಿಂಗ್ ಸಿಸ್ಟಮ್ಸ್",
    faqA2: "ಒಂದೇ ರೀತಿಯ ನಿರ್ದೇಶಾಂಕಗಳು ಸಕ್ರಿಯ ಫೈಲ್‌ಗಳಿಗೆ ಕ್ರಿಯಾತ್ಮಕವಾಗಿ ಹೊಂದಿಕೆಯಾಗುತ್ತವೆ, ಡಬಲ್ ಎಂಟ್ರಿ ಇಲ್ಲದೆ ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಅನ್ನು ನವೀಕರಿಸುತ್ತವೆ.",
    loginTitle: "ನಾಗರಿಕ ಮತ್ತು ಸಿಬ್ಬಂದಿ ಪೋರ್ಟಲ್",
    loginDesc: "ಸುರಕ್ಷಿತ ಸೆಷನ್ ಸ್ಥಾಪಿಸಿ",
    formName: "ಪೂರ್ಣ ಹೆಸರು",
    formRole: "ಪಾತ್ರ",
    authSubmit: "ಸುರಕ್ಷಿತ ಸೆಷನ್ ಸ್ಥಾಪಿಸಿ",
    aiDeskTitle: "ಸಿವಿಕ್-AI ಅಸಿಸ್ಟೆಂಟ್",
    aiStatus: "ಆನ್‌ಲೈನ್ • ಸುರಕ್ಷಿತ ಎನ್‌ಕ್ರಿಪ್ಶನ್",
    nodeTypeAnon: "ಅನಾಮಧೇಯ ನೋಡ್",
    nodeTypeActive: "ದೃಢೀಕೃತ ನೋಡ್",
    uploadHeadline: "ನಾಗರಿಕ ಸಮಸ್ಯೆಯ ಫೋಟೋ ಅಪ್ಲೋಡ್ ಮಾಡಿ",
    uploadDesc: "ಕೆಳಗಿನ ಗ್ಯಾಲರಿಯಿಂದ ಚಿತ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ.",
    unlockWorkspace: "ಸಿಮ್ಯುಲೇಟರ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಕಾರ್ಯಕ್ಷೇತ್ರವನ್ನು ಅನ್‌ಲಾಕ್ ಮಾಡಿ",
    aiProcessing: "ನ್ಯೂರಲ್ ನೆಟ್ ಮೌಲ್ಯಮಾಪನ ಸಕ್ರಿಯವಾಗಿದೆ...",
    receiptHeader: "✅ ಪರಿಶೀಲಿಸಿದ ಪುರಸಭೆಯ ಕೆಲಸದ ಆದೇಶ ದಾಖಲೆ",
    recId: "ಟ್ರ್ಯಾಕಿಂಗ್ ಉಲ್ಲೇಖ",
    recLoc: "ಸ್ಥಳ",
    recDesc: "ವರ್ಗೀಕರಣ",
    recSla: "SLA",
    recVotes: "ಪ್ರಾಮುಖ್ಯತೆಯ ಮತಗಳು",
    btnUpvote: "👍 ನನಗೂ ಅನ್ವಯಿಸುತ್ತದೆ / ನನ್ನ ನೆರೆಹೊರೆಯ ಮೇಲೆ ಪರಿಣಾಮ ಬೀರುತ್ತದೆ",
    voiceTrigger: "ಓದಿ ಹೇಳಿ",
    shelfTitle: "ಗ್ಯಾಲರಿಯಿಂದ ಚಿತ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    m1: "ಪರಿಹಾರ ಚಕ್ರದ ಸಮಯ",
    m2: "ಸಕ್ರಿಯ ಕ್ಷೇತ್ರ ನಿಯೋಜನೆಗಳು",
    m3: "ರಿಜಿಸ್ಟ್ರಿ ದರ",
    heatmapTitle: "ನಗರ-ವ್ಯಾಪಕ ಉಲ್ಬಣ ಓವರ್ಲೇ",
    spatialActive: "ಸಂವಾದಾತ್ಮಕ ಪ್ರಾದೇಶಿಕ ಓವರ್ಲೇ ಸಕ್ರಿಯವಾಗಿದೆ",
    adminTitle: "ಮುನ್ಸಿಪಲ್ ಡಿಸ್ಪ್ಯಾಚ್ ಕಮಾಂಡ್",
    adminDesc: "ವರದಿಗಳನ್ನು ನಿರ್ವಹಿಸಿ, ಮತ್ತು SLA ಟ್ರ್ಯಾಕ್ ಮಾಡಿ.",
    btnFf: "⏩ ಫಾಸ್ಟ್-ಫಾರ್ವರ್ಡ್ ಸಮಯ (SLA ಉಲ್ಲಂಘನೆ)",
    thId: "ಐಡಿ", thHazard: "ಅಪಾಯದ ವಿವರ", thUrgency: "ಸ್ಥಿತಿ", thSla: "SLA ಟ್ರ್ಯಾಕರ್", thAction: "ಕ್ರಮ",
    navHome: "ಮುಖಪುಟ", navReport: "ವರದಿ", navGrid: "ಗ್ರಿಡ್", navAdmin: "ಸಿಬ್ಬಂದಿ ಪ್ಯಾನಲ್",
    voicePrompt: "ಸಿವಿಕ್ ಶೀಲ್ಡ್‌ಗೆ ಸುಸ್ವಾಗತ. ಅಪಾಯವನ್ನು ವರದಿ ಮಾಡಲು, ಲಾಗ್ ಇನ್ ಮಾಡಿ ಮತ್ತು ಫೋಟೋ ಆಯ್ಕೆಮಾಡಿ.",
    alertFake: "❌ ಅಮಾನ್ಯ ಚಿತ್ರ ಪತ್ತೆಯಾಗಿದೆ: ಸಾರ್ವಜನಿಕ ಮೂಲಸೌಕರ್ಯದ ಅಪಾಯವನ್ನು ಹೊಂದಿಲ್ಲ.",
    alertDup: "📢 ಈಗಾಗಲೇ ವರದಿ ಮಾಡಲಾಗಿದೆ! ಈ ಸ್ಥಳದಲ್ಲಿ ಈ ಸಮಸ್ಯೆಯನ್ನು ಗುರುತಿಸಲಾಗಿದೆ.",
    alertOffline: "⚠️ ಆಫ್‌ಲೈನ್: ವರದಿಯನ್ನು ಸ್ಥಳೀಯವಾಗಿ ಉಳಿಸಲಾಗಿದೆ ಮತ್ತು ಸಂಪರ್ಕ ಬಂದ ತಕ್ಷಣ ಸಿಂಕ್ ಆಗುತ್ತದೆ.",
    alertBreach: "⚠️ ಉಲ್ಬಣಗೊಂಡ ಎಚ್ಚರಿಕೆ: ವರದಿ ಮಾಡಿದ ಸಮಸ್ಯೆ SLA ಅನ್ನು ಉಲ್ಲಂಘಿಸಿದೆ.",
    unassignedSla: "ಹಂಚಿಕೆಗಾಗಿ ಕಾಯಲಾಗುತ್ತಿದೆ",
    title: "ನಾಗರಿಕ ಮತ್ತು ಸಿಬ್ಬಂದಿ ಪೋರ್ಟಲ್",
    subtitle: "ಸುರಕ್ಷಿತ ಸೆಷನ್ ಸ್ಥಾಪಿಸಿ",
    labelName: "ಪೂರ್ಣ ಹೆಸರು",
    placeholderName: "ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರನ್ನು ನಮೂದಿಸಿ",
    labelRole: "ಪಾತ್ರ",
    roleCitizen: "ನಾಗರಿಕ",
    roleAdmin: "ನಗರ ನಿರ್ವಹಣಾಧಿಕಾರಿ/ಸಿಬ್ಬಂದಿ",
    labelBranch: "ಮಹಾನಗರ ಪಾಲಿಕೆ",
    btnSubmit: "ಸುರಕ್ಷಿತ ಸೆಷನ್ ಸ್ಥಾಪಿಸಿ",
    btnCancel: "ರದ್ದುಗೊಳಿಸಿ ಮತ್ತು ಮುಖಪುಟಕ್ಕೆ ಹಿಂತಿರುಗಿ"
  }
};

export const localHazardDataset = [
  { id: "TK-4431", title: "Structural Fissure on Metro Pillar Bridge", loc: "MG Road Metro Pillar Structural, Bengaluru", img: "/images/incidents/pothole_01.jpg", type: "hazard" },
  { id: "TK-9081", title: "Clogged Underground Storm Drainage Overflow", loc: "Koramangala 4th Block Drainage, Bengaluru", img: "/images/incidents/drain_01.jpg", type: "hazard" },
  { id: "TK-1102", title: "Exposed High-Voltage Distribution Cables", loc: "Indiranagar 100ft Road Intersection, Bengaluru", img: "/images/incidents/light_01.jpg", type: "hazard" },
  { id: "TK-5690", title: "Deep Arterial Pothole Array Layout Erosion", loc: "HSR Layout Junction Roadbed, Bengaluru", img: "/images/incidents/pothole_01.jpg", type: "hazard" },
  { id: "TK-3341", title: "Ruptured Water Main Distribution Spillage", loc: "Nayandahalli Intersect Water Main, Bengaluru", img: "/images/incidents/drain_01.jpg", type: "hazard" },
  { id: "TK-8872", title: "Damaged Unlit High-Mast Streetlight Tower", loc: "Whitefield Outer Ring Road Tower, Bengaluru", img: "/images/incidents/light_01.jpg", type: "hazard" },
  { id: "TK-2991", title: "Illegal Hazardous Industrial Waste Dump Site", loc: "Electronic City Phase 1 Highway, Bengaluru", img: "/images/incidents/waste_01.jpg", type: "hazard" },
  { id: "TK-7762", title: "Unprotected Open Sump Cavity on Walkway", loc: "Jayanagar 4th T Block Sidewalk, Bengaluru", img: "/images/incidents/manhole_01.jpg", type: "hazard" },
  { id: "TK-6123", title: "Leaning Electrical Utility Transmission Pole", loc: "Malleswaram 18th Cross Overhead, Bengaluru", img: "/images/incidents/light_01.jpg", type: "hazard" },
  { id: "TK-1049", title: "Submerged Roadbed Open Sewer Overflow", loc: "Hebbal Flyover Service Pipeline, Bengaluru", img: "/images/incidents/waste_01.jpg", type: "hazard" },
  { id: "TK-1211", title: "Broken Concrete Footpath Slabs", loc: "Commercial Street Pedestrian Walk, Bengaluru", img: "/images/incidents/pothole_01.jpg", type: "hazard" },
  { id: "TK-1312", title: "Toppled Traffic Isolation Guard Rail", loc: "Silk Board Flyover Ramp, Bengaluru", img: "/images/incidents/pothole_01.jpg", type: "hazard" },
  { id: "TK-1413", title: "Uprooted Tree Blocking Public Thoroughfare", loc: "Sadashivanagar 5th Main Avenue, Bengaluru", img: "/images/incidents/waste_01.jpg", type: "hazard" },
  { id: "TK-1514", title: "Uncontrolled Fire at Local Refuse Dump", loc: "Bellandur Lake Boundary Zone, Bengaluru", img: "/images/incidents/waste_01.jpg", type: "hazard" },
  { id: "TK-1615", title: "Sinking Asphalt Cavity Land Collapse", loc: "Rajajinagar Outer Ring Segment, Bengaluru", img: "/images/incidents/pothole_01.jpg", type: "hazard" }
];

export const nonHazardImages = [
  { title: 'Pothole Hazard', img: '/images/incidents/pothole_01.jpg', loc: 'Downtown Road' },
  { title: 'Overflowing Waste', img: '/images/incidents/waste_01.jpg', loc: 'Market Area' },
  { title: 'Damaged Streetlight', img: '/images/incidents/light_01.jpg', loc: 'Main Street' },
  { title: 'Broken Manhole', img: '/images/incidents/manhole_01.jpg', loc: 'Suburban Street' },
  { title: 'Clogged Drain', img: '/images/incidents/drain_01.jpg', loc: 'North Avenue' },
  { title: 'Pothole Hazard', img: '/images/incidents/pothole_01.jpg', loc: 'East Boulevard' },
  { title: 'Overflowing Waste', img: '/images/incidents/waste_01.jpg', loc: 'West Side Park' },
  { title: 'Damaged Streetlight', img: '/images/incidents/light_01.jpg', loc: 'South Station' },
  { title: 'Broken Manhole', img: '/images/incidents/manhole_01.jpg', loc: 'Central Hub' },
  { title: 'Clogged Drain', img: '/images/incidents/drain_01.jpg', loc: 'River Walk' },
  { title: 'Pothole Hazard', img: '/images/incidents/pothole_01.jpg', loc: 'Highland Ave' },
  { title: 'Overflowing Waste', img: '/images/incidents/waste_01.jpg', loc: 'Old Town Square' },
  { title: 'Damaged Streetlight', img: '/images/incidents/light_01.jpg', loc: 'Industrial Park' },
  { title: 'Broken Manhole', img: '/images/incidents/manhole_01.jpg', loc: 'University Campus' },
  { title: 'Clogged Drain', img: '/images/incidents/drain_01.jpg', loc: 'Shopping District' }
];
